name: filters-activity-types

on: 
    pull_request:
        types:
           # - opened
           # - synchronize
            - closed
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Running whenerver PR is now closed"