name: workflow-event

on: 
    workflow_dispatch: # here in workflow dispatch event requires manual triggering job inside github -> Actions
    pull_request:
    schedule:
        - cron: '*/5 * * * *' # we can't schedule for every one minute 
    
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: show trigger info
              run: "echo This Job been triggered by ${{github.actor_id}} event."